name: hello world workflow

on:
  push:
    branches:
      - main

jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.0
      - name: first strip
        run: echo "hello world"
        shell: bash
