name: hello world workflow

on:
  push:
    branches:
      - main

jobs:
  name: hello world
  runs-on: ubuntu-latest
  steps:
    - name: first strip
      run: echo "hello world"
      shell: bash

